development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: xnotifyc_development
  pool: 5
  username: admin
  password: password
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: railsHUY_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: xnotifyc_development
  pool: 5
  username: xnotifyc_razir
  password: 184418
